USER_EMAIL_MAX_LENGTH = 254
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
TAG_SLUG_REGEX = r'^[-a-zA-Z0-9_]+$'
TAG_SLUG_ERROR_MESSAGE = 'Slug can only contain letters, numbers, hyphens and underscores'

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_IMAGE_UPLOAD_PATH = 'recipes/images/'

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
